{% set version = "0.1.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-getoptlong
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GetoptLong_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GetoptLong/GetoptLong_{{ version }}.tar.gz
  sha256: 6c0edb7233b79fb7f4789a825e8e7d7eee50b5e85b7fd5b7d74b9440fd9e1dd1

build:
  merge_build_host: True  # [win]
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-globaloptions >=0.1.0
    - r-rjson
  run:
    - r-base
    - r-globaloptions >=0.1.0
    - r-rjson

test:
  commands:
    - $R -e "library('GetoptLong')"  # [not win]
    - "\"%R%\" -e \"library('GetoptLong')\""  # [win]

about:
  home: https://github.com/jokergoo/GetoptLong
  license: MIT
  summary: This is yet another command-line argument parser which wraps the powerful Perl module
    Getopt::Long and with some adaptation for easier use in R. It also provides a simple
    way for variable interpolation in R.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
