appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: it3mt/X/AFtqFLCFW9SNXJkrekaJCpRp028B5hj+z3tZpy4ZlY8/ey+kdfAPiV9v5T80H7LiaEZq3C9KDgUoV2KG3opCDC4pmPNjY9FNrmhVHGT5/Ur0AlgCGf/rJaHXX5C8g2B+fDvDsQO9awjTRDOSEaQcpGlJc/QZ9xjnIJbAAhUwx3zuQf7W1OYw+RJ3AxB6fWz2JYR4gBWAjWyOG9oyzPqCXu3dvLI+hawwNGtIhN4blCVyCoE0b0TI9vs9It/S6748mbrAn5Vf0LDJZXQfD5D4GKziiJGdL1RYIs+4Kc/oW8LSpJEvn40dkviR0M/71WEVuJnNrp0wy13XYecxRGgDJXqCNCql4iBJrnNl6th9JjnZ3RwuXWVc5Z7KJLgx6i/rwwtckcxzypmAT2RNndhvx7ltHds0TPFUw8NM+jGfQ/gj573ZPDhJgc/SxNxSe/+OxY1OQ/+BmFiL1kwlt68UGHu9zlXFor7PhvbQKKBoLhne9T8I1YCelZ3KdkKtvO2yDrivXSRaYgCflr7LT+h987w0qe6PhsQhZExnd2joh2+ozrH1MTINftjZGdvSSvMkYGiUTFtKt/fpUDw4RnIRvggOeZn/SjX3SGiP5Il2WEHxXJ5D0CViQL/JbfzT6Izj2IE7UiVfrB7g5Che8zjUk5jfM3kzTBsiweY=}
bot:
  automerge: true
